-- ECW E-Commerce Database Schema
-- PostgreSQL / Supabase

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  avatar VARCHAR(500),
  phone VARCHAR(20),
  role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  google_id VARCHAR(255) UNIQUE,
  is_verified BOOLEAN DEFAULT false,
  reset_token VARCHAR(500),
  reset_token_expires TIMESTAMPTZ,
  otp VARCHAR(6),
  otp_expires TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS addresses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  zip_code VARCHAR(20) NOT NULL,
  country VARCHAR(100) DEFAULT 'India',
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_addresses_user ON addresses (user_id);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  description TEXT,
  image VARCHAR(500),
  parent_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories (slug);
CREATE INDEX IF NOT EXISTS idx_categories_active ON categories (is_active);
CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories (parent_id);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(300) NOT NULL UNIQUE,
  description TEXT,
  short_description VARCHAR(500),
  price NUMERIC(10, 2) NOT NULL,
  compare_price NUMERIC(10, 2),
  cost_price NUMERIC(10, 2),
  sku VARCHAR(100) UNIQUE,
  barcode VARCHAR(100),
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  brand VARCHAR(100),
  tags TEXT[] NOT NULL DEFAULT '{}',
  stock_quantity INTEGER DEFAULT 0,
  low_stock_threshold INTEGER DEFAULT 5,
  weight NUMERIC(8, 2),
  images JSONB,
  specifications JSONB,
  is_featured BOOLEAN DEFAULT false,
  popularity_score NUMERIC(8, 2) DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'out_of_stock', 'draft')),
  discount_percent NUMERIC(5, 2) DEFAULT 0,
  tax_rate NUMERIC(5, 2) DEFAULT 0,
  sales_count INTEGER DEFAULT 0,
  rating NUMERIC(3, 2) DEFAULT 0.00,
  review_count INTEGER DEFAULT 0,
  search_vector TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(brand, '')), 'B') ||
    setweight(to_tsvector('english', array_to_string(coalesce(tags, '{}'::text[]), ' ')), 'B') ||
    setweight(to_tsvector('english', coalesce(short_description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'D') ||
    setweight(to_tsvector('english', coalesce(sku, '')), 'D')
  ) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_slug ON products (slug);
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON products (is_active);
CREATE INDEX IF NOT EXISTS idx_products_featured ON products (is_featured);
CREATE INDEX IF NOT EXISTS idx_products_price ON products (price);
CREATE INDEX IF NOT EXISTS idx_products_rating ON products (rating);
CREATE INDEX IF NOT EXISTS idx_products_sales ON products (sales_count);
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING GIN (to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '')));
CREATE INDEX IF NOT EXISTS idx_products_active_status ON products (is_active, status);
CREATE INDEX IF NOT EXISTS idx_products_search_vector ON products USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON products USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_brand_trgm ON products USING GIN (lower(brand) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_description_trgm ON products USING GIN (lower(description) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_tags_gin ON products USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_products_tags_trgm ON products USING GIN ((array_to_string(tags, ' ')) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_popularity ON products (popularity_score DESC);
CREATE INDEX IF NOT EXISTS idx_categories_name_trgm ON categories USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_categories_slug_trgm ON categories USING GIN (lower(slug) gin_trgm_ops);

DROP TRIGGER IF EXISTS set_products_updated_at ON products;
CREATE TRIGGER set_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS search_queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  session_id VARCHAR(80),
  query TEXT NOT NULL,
  normalized_query TEXT NOT NULL,
  corrected_query TEXT,
  result_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_search_queries_user_created ON search_queries (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_queries_session_created ON search_queries (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_queries_normalized ON search_queries (normalized_query);
CREATE INDEX IF NOT EXISTS idx_search_queries_normalized_trgm ON search_queries USING GIN (normalized_query gin_trgm_ops);

CREATE TABLE IF NOT EXISTS search_terms (
  normalized_query TEXT PRIMARY KEY,
  display_query TEXT NOT NULL,
  search_count INTEGER NOT NULL DEFAULT 0,
  result_count INTEGER DEFAULT 0,
  last_searched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_search_terms_count ON search_terms (search_count DESC, last_searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_terms_display_trgm ON search_terms USING GIN (lower(display_query) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS product_search_metrics (
  product_id INTEGER PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
  impressions BIGINT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  ctr NUMERIC(10, 6) GENERATED ALWAYS AS (
    CASE
      WHEN impressions = 0 THEN 0
      ELSE clicks::numeric / impressions::numeric
    END
  ) STORED,
  last_impression_at TIMESTAMPTZ,
  last_click_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_search_metrics_ctr ON product_search_metrics (ctr DESC);

DROP TRIGGER IF EXISTS set_product_search_metrics_updated_at ON product_search_metrics;
CREATE TRIGGER set_product_search_metrics_updated_at
BEFORE UPDATE ON product_search_metrics
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS recently_searched_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  session_id VARCHAR(80),
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  search_query_id BIGINT REFERENCES search_queries(id) ON DELETE SET NULL,
  query TEXT,
  searched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recently_searched_items_user ON recently_searched_items (user_id, searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_recently_searched_items_session ON recently_searched_items (session_id, searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_recently_searched_items_product ON recently_searched_items (product_id);

CREATE TABLE IF NOT EXISTS product_variants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  value VARCHAR(100) NOT NULL,
  price_adjustment NUMERIC(10, 2) DEFAULT 0.00,
  stock_quantity INTEGER DEFAULT 0,
  sku VARCHAR(100),
  image VARCHAR(500),
  is_active BOOLEAN DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product ON product_variants (product_id);

CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255),
  is_primary BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images (product_id);

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title VARCHAR(255),
  comment TEXT,
  images JSONB,
  is_verified_purchase BOOLEAN DEFAULT false,
  is_approved BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_review UNIQUE (product_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_approved ON reviews (is_approved);

CREATE TABLE IF NOT EXISTS cart (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  session_id VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT cart_owner_required CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_cart_user ON cart (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_session ON cart (session_id);

DROP TRIGGER IF EXISTS set_cart_updated_at ON cart;
CREATE TRIGGER set_cart_updated_at
BEFORE UPDATE ON cart
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS cart_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id INTEGER NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  variant_id INTEGER REFERENCES product_variants(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items (cart_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_cart_product ON cart_items (cart_id, product_id, coalesce(variant_id, 0));

CREATE TABLE IF NOT EXISTS wishlist (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_wishlist UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_user ON wishlist (user_id);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) NOT NULL UNIQUE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
  payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  payment_method VARCHAR(50),
  payment_id VARCHAR(255),
  subtotal NUMERIC(10, 2) NOT NULL,
  shipping_cost NUMERIC(10, 2) DEFAULT 0.00,
  tax_amount NUMERIC(10, 2) DEFAULT 0.00,
  discount_amount NUMERIC(10, 2) DEFAULT 0.00,
  total_amount NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'INR',
  shipping_address_id INTEGER REFERENCES addresses(id) ON DELETE SET NULL,
  billing_address_id INTEGER REFERENCES addresses(id) ON DELETE SET NULL,
  coupon_code VARCHAR(50),
  notes TEXT,
  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders (order_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_payment ON orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders (created_at);

DROP TRIGGER IF EXISTS set_orders_updated_at ON orders;
CREATE TRIGGER set_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  variant_id INTEGER REFERENCES product_variants(id) ON DELETE SET NULL,
  product_name VARCHAR(255) NOT NULL,
  product_image VARCHAR(500),
  variant_info VARCHAR(255),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  total_price NUMERIC(10, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);

CREATE TABLE IF NOT EXISTS order_tracking (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_tracking_order ON order_tracking (order_id);

CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  discount_value NUMERIC(10, 2) NOT NULL,
  min_order_amount NUMERIC(10, 2) DEFAULT 0,
  max_discount NUMERIC(10, 2),
  usage_limit INTEGER,
  used_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  starts_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons (code);
CREATE INDEX IF NOT EXISTS idx_coupons_active ON coupons (is_active);

CREATE TABLE IF NOT EXISTS banners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  subtitle VARCHAR(500),
  image_url VARCHAR(500) NOT NULL,
  link_url VARCHAR(500),
  btn_text VARCHAR(100),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_banners_active ON banners (is_active);

CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'INR',
  payment_method VARCHAR(50),
  payment_id VARCHAR(255),
  status VARCHAR(50),
  response_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transactions_order ON transactions (order_id);
CREATE INDEX IF NOT EXISTS idx_transactions_payment ON transactions (payment_id);

CREATE TABLE IF NOT EXISTS recently_viewed (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  viewed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recently_viewed_user ON recently_viewed (user_id);

-- Seed data: Admin user placeholder password must be replaced before production use.
INSERT INTO users (name, email, password, role, is_verified)
VALUES ('Admin', 'admin@ecwshop.com', '$2a$10$YourHashedPasswordHere', 'admin', true)
ON CONFLICT (email) DO NOTHING;

INSERT INTO categories (name, slug, description, is_active) VALUES
('Electronics', 'electronics', 'Latest gadgets and electronic devices', true),
('Fashion', 'fashion', 'Trendy clothing and accessories', true),
('Home & Living', 'home-living', 'Beautiful home decor and furniture', true),
('Beauty', 'beauty', 'Skincare, makeup and beauty products', true),
('Books', 'books', 'Books across all genres', true),
('Sports', 'sports', 'Sports equipment and activewear', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO categories (name, slug, description, parent_id, is_active) VALUES
('Smartphones', 'smartphones', 'Latest smartphones', (SELECT id FROM categories WHERE slug = 'electronics'), true),
('Laptops', 'laptops', 'Notebooks and laptops', (SELECT id FROM categories WHERE slug = 'electronics'), true),
('Headphones', 'headphones', 'Audio devices', (SELECT id FROM categories WHERE slug = 'electronics'), true),
('Men Clothing', 'men-clothing', 'Men fashion', (SELECT id FROM categories WHERE slug = 'fashion'), true),
('Women Clothing', 'women-clothing', 'Women fashion', (SELECT id FROM categories WHERE slug = 'fashion'), true),
('Furniture', 'furniture', 'Home furniture', (SELECT id FROM categories WHERE slug = 'home-living'), true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (name, slug, description, price, compare_price, category_id, brand, tags, stock_quantity, images, is_featured, status, rating, review_count, sales_count, popularity_score) VALUES
('Wireless Noise Cancelling Headphones', 'wireless-nc-headphones', 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and comfortable over-ear design.', 249.99, 349.99, (SELECT id FROM categories WHERE slug = 'headphones'), 'V Audio', ARRAY['wireless', 'headphones', 'noise cancellation', 'audio']::text[], 50, '["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"]'::jsonb, true, 'active', 4.5, 128, 220, 82),
('Smart Watch Pro', 'smart-watch-pro', 'Advanced smartwatch with health monitoring, GPS, and 7-day battery life.', 199.99, 299.99, (SELECT id FROM categories WHERE slug = 'electronics'), 'V Tech', ARRAY['smartwatch', 'fitness', 'gps', 'wearable']::text[], 35, '["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600"]'::jsonb, true, 'active', 4.3, 89, 160, 76),
('Premium Leather Backpack', 'premium-leather-backpack', 'Handcrafted genuine leather backpack with laptop compartment and USB charging port.', 89.99, 129.99, (SELECT id FROM categories WHERE slug = 'men-clothing'), 'V Wear', ARRAY['backpack', 'leather', 'travel', 'laptop bag']::text[], 25, '["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"]'::jsonb, true, 'active', 4.7, 56, 118, 70),
('Minimalist Desk Lamp', 'minimalist-desk-lamp', 'Modern LED desk lamp with adjustable brightness, color temperature, and wireless charging base.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'furniture'), 'V Home', ARRAY['desk lamp', 'led', 'home office', 'lighting']::text[], 100, '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600"]'::jsonb, true, 'active', 4.2, 34, 90, 64),
('Organic Skincare Set', 'organic-skincare-set', 'Complete natural skincare routine with cleanser, serum, and moisturizer.', 45.99, 65.99, (SELECT id FROM categories WHERE slug = 'beauty'), 'V Glow', ARRAY['skincare', 'organic', 'beauty', 'cleanser']::text[], 80, '["https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=600"]'::jsonb, true, 'active', 4.8, 92, 145, 79),
('Bluetooth Portable Speaker', 'bluetooth-speaker', 'Waterproof portable speaker with 360-degree sound and 20-hour battery.', 79.99, 99.99, (SELECT id FROM categories WHERE slug = 'headphones'), 'V Audio', ARRAY['bluetooth', 'speaker', 'portable', 'waterproof']::text[], 60, '["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600"]'::jsonb, false, 'active', 4.1, 45, 104, 58),
('Samsung Galaxy S24', 'samsung-galaxy-s24', 'Samsung Galaxy smartphone with AMOLED display, high performance camera system, 5G connectivity and all-day battery life.', 799.99, 899.99, (SELECT id FROM categories WHERE slug = 'smartphones'), 'Samsung', ARRAY['samsung', 'galaxy', 'android', 'smartphone', '5g']::text[], 45, '["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600"]'::jsonb, true, 'active', 4.6, 156, 260, 88),
('Apple iPhone 15', 'apple-iphone-15', 'Apple iPhone with Super Retina display, A-series performance, advanced camera features and iOS experience.', 899.99, 999.99, (SELECT id FROM categories WHERE slug = 'smartphones'), 'Apple', ARRAY['iphone', 'apple', 'ios', 'smartphone', '5g']::text[], 40, '["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600"]'::jsonb, true, 'active', 4.7, 210, 310, 92)
ON CONFLICT (slug) DO NOTHING;
