-- Flipkart/Amazon-style product search for Supabase PostgreSQL.
-- Run this in Supabase SQL editor or as a Supabase migration.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS popularity_score NUMERIC(8, 2) NOT NULL DEFAULT 0;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS search_vector TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(brand, '')), 'B') ||
    setweight(to_tsvector('english', array_to_string(coalesce(tags, '{}'::text[]), ' ')), 'B') ||
    setweight(to_tsvector('english', coalesce(short_description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'D') ||
    setweight(to_tsvector('english', coalesce(sku, '')), 'D')
  ) STORED;

CREATE TABLE IF NOT EXISTS search_queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  session_id VARCHAR(80),
  query TEXT NOT NULL,
  normalized_query TEXT NOT NULL,
  corrected_query TEXT,
  result_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS search_terms (
  normalized_query TEXT PRIMARY KEY,
  display_query TEXT NOT NULL,
  search_count INTEGER NOT NULL DEFAULT 0,
  result_count INTEGER DEFAULT 0,
  last_searched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_search_metrics (
  product_id INTEGER PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
  impressions BIGINT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  ctr NUMERIC(10, 6) GENERATED ALWAYS AS (
    CASE
      WHEN impressions = 0 THEN 0
      ELSE clicks::numeric / impressions::numeric
    END
  ) STORED,
  last_impression_at TIMESTAMPTZ,
  last_click_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS set_product_search_metrics_updated_at ON product_search_metrics;
CREATE TRIGGER set_product_search_metrics_updated_at
BEFORE UPDATE ON product_search_metrics
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS recently_searched_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  session_id VARCHAR(80),
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  search_query_id BIGINT REFERENCES search_queries(id) ON DELETE SET NULL,
  query TEXT,
  searched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_active_status ON products (is_active, status);
CREATE INDEX IF NOT EXISTS idx_products_search_vector ON products USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON products USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_brand_trgm ON products USING GIN (lower(brand) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_description_trgm ON products USING GIN (lower(description) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_tags_gin ON products USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_products_tags_trgm ON products USING GIN ((array_to_string(tags, ' ')) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_popularity ON products (popularity_score DESC);

CREATE INDEX IF NOT EXISTS idx_categories_name_trgm ON categories USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_categories_slug_trgm ON categories USING GIN (lower(slug) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_search_queries_user_created ON search_queries (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_queries_session_created ON search_queries (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_queries_normalized ON search_queries (normalized_query);
CREATE INDEX IF NOT EXISTS idx_search_queries_normalized_trgm ON search_queries USING GIN (normalized_query gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_search_terms_count ON search_terms (search_count DESC, last_searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_terms_display_trgm ON search_terms USING GIN (lower(display_query) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_product_search_metrics_ctr ON product_search_metrics (ctr DESC);
CREATE INDEX IF NOT EXISTS idx_recently_searched_items_user ON recently_searched_items (user_id, searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_recently_searched_items_session ON recently_searched_items (session_id, searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_recently_searched_items_product ON recently_searched_items (product_id);
